require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhonetypesController do

  # This should return the minimal set of attributes required to create a valid
  # Phonetype. As you add validations to Phonetype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhonetypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all phonetypes as @phonetypes" do
      phonetype = Phonetype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:phonetypes).should eq([phonetype])
    end
  end

  describe "GET show" do
    it "assigns the requested phonetype as @phonetype" do
      phonetype = Phonetype.create! valid_attributes
      get :show, {:id => phonetype.to_param}, valid_session
      assigns(:phonetype).should eq(phonetype)
    end
  end

  describe "GET new" do
    it "assigns a new phonetype as @phonetype" do
      get :new, {}, valid_session
      assigns(:phonetype).should be_a_new(Phonetype)
    end
  end

  describe "GET edit" do
    it "assigns the requested phonetype as @phonetype" do
      phonetype = Phonetype.create! valid_attributes
      get :edit, {:id => phonetype.to_param}, valid_session
      assigns(:phonetype).should eq(phonetype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Phonetype" do
        expect {
          post :create, {:phonetype => valid_attributes}, valid_session
        }.to change(Phonetype, :count).by(1)
      end

      it "assigns a newly created phonetype as @phonetype" do
        post :create, {:phonetype => valid_attributes}, valid_session
        assigns(:phonetype).should be_a(Phonetype)
        assigns(:phonetype).should be_persisted
      end

      it "redirects to the created phonetype" do
        post :create, {:phonetype => valid_attributes}, valid_session
        response.should redirect_to(Phonetype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phonetype as @phonetype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phonetype.any_instance.stub(:save).and_return(false)
        post :create, {:phonetype => {  }}, valid_session
        assigns(:phonetype).should be_a_new(Phonetype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phonetype.any_instance.stub(:save).and_return(false)
        post :create, {:phonetype => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phonetype" do
        phonetype = Phonetype.create! valid_attributes
        # Assuming there are no other phonetypes in the database, this
        # specifies that the Phonetype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Phonetype.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => phonetype.to_param, :phonetype => { "these" => "params" }}, valid_session
      end

      it "assigns the requested phonetype as @phonetype" do
        phonetype = Phonetype.create! valid_attributes
        put :update, {:id => phonetype.to_param, :phonetype => valid_attributes}, valid_session
        assigns(:phonetype).should eq(phonetype)
      end

      it "redirects to the phonetype" do
        phonetype = Phonetype.create! valid_attributes
        put :update, {:id => phonetype.to_param, :phonetype => valid_attributes}, valid_session
        response.should redirect_to(phonetype)
      end
    end

    describe "with invalid params" do
      it "assigns the phonetype as @phonetype" do
        phonetype = Phonetype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phonetype.any_instance.stub(:save).and_return(false)
        put :update, {:id => phonetype.to_param, :phonetype => {  }}, valid_session
        assigns(:phonetype).should eq(phonetype)
      end

      it "re-renders the 'edit' template" do
        phonetype = Phonetype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phonetype.any_instance.stub(:save).and_return(false)
        put :update, {:id => phonetype.to_param, :phonetype => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phonetype" do
      phonetype = Phonetype.create! valid_attributes
      expect {
        delete :destroy, {:id => phonetype.to_param}, valid_session
      }.to change(Phonetype, :count).by(-1)
    end

    it "redirects to the phonetypes list" do
      phonetype = Phonetype.create! valid_attributes
      delete :destroy, {:id => phonetype.to_param}, valid_session
      response.should redirect_to(phonetypes_url)
    end
  end

end
