require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PhonenumbersController do

  # This should return the minimal set of attributes required to create a valid
  # Phonenumber. As you add validations to Phonenumber, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PhonenumbersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all phonenumbers as @phonenumbers" do
      phonenumber = Phonenumber.create! valid_attributes
      get :index, {}, valid_session
      assigns(:phonenumbers).should eq([phonenumber])
    end
  end

  describe "GET show" do
    it "assigns the requested phonenumber as @phonenumber" do
      phonenumber = Phonenumber.create! valid_attributes
      get :show, {:id => phonenumber.to_param}, valid_session
      assigns(:phonenumber).should eq(phonenumber)
    end
  end

  describe "GET new" do
    it "assigns a new phonenumber as @phonenumber" do
      get :new, {}, valid_session
      assigns(:phonenumber).should be_a_new(Phonenumber)
    end
  end

  describe "GET edit" do
    it "assigns the requested phonenumber as @phonenumber" do
      phonenumber = Phonenumber.create! valid_attributes
      get :edit, {:id => phonenumber.to_param}, valid_session
      assigns(:phonenumber).should eq(phonenumber)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Phonenumber" do
        expect {
          post :create, {:phonenumber => valid_attributes}, valid_session
        }.to change(Phonenumber, :count).by(1)
      end

      it "assigns a newly created phonenumber as @phonenumber" do
        post :create, {:phonenumber => valid_attributes}, valid_session
        assigns(:phonenumber).should be_a(Phonenumber)
        assigns(:phonenumber).should be_persisted
      end

      it "redirects to the created phonenumber" do
        post :create, {:phonenumber => valid_attributes}, valid_session
        response.should redirect_to(Phonenumber.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved phonenumber as @phonenumber" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phonenumber.any_instance.stub(:save).and_return(false)
        post :create, {:phonenumber => {  }}, valid_session
        assigns(:phonenumber).should be_a_new(Phonenumber)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Phonenumber.any_instance.stub(:save).and_return(false)
        post :create, {:phonenumber => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested phonenumber" do
        phonenumber = Phonenumber.create! valid_attributes
        # Assuming there are no other phonenumbers in the database, this
        # specifies that the Phonenumber created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Phonenumber.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => phonenumber.to_param, :phonenumber => { "these" => "params" }}, valid_session
      end

      it "assigns the requested phonenumber as @phonenumber" do
        phonenumber = Phonenumber.create! valid_attributes
        put :update, {:id => phonenumber.to_param, :phonenumber => valid_attributes}, valid_session
        assigns(:phonenumber).should eq(phonenumber)
      end

      it "redirects to the phonenumber" do
        phonenumber = Phonenumber.create! valid_attributes
        put :update, {:id => phonenumber.to_param, :phonenumber => valid_attributes}, valid_session
        response.should redirect_to(phonenumber)
      end
    end

    describe "with invalid params" do
      it "assigns the phonenumber as @phonenumber" do
        phonenumber = Phonenumber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phonenumber.any_instance.stub(:save).and_return(false)
        put :update, {:id => phonenumber.to_param, :phonenumber => {  }}, valid_session
        assigns(:phonenumber).should eq(phonenumber)
      end

      it "re-renders the 'edit' template" do
        phonenumber = Phonenumber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Phonenumber.any_instance.stub(:save).and_return(false)
        put :update, {:id => phonenumber.to_param, :phonenumber => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested phonenumber" do
      phonenumber = Phonenumber.create! valid_attributes
      expect {
        delete :destroy, {:id => phonenumber.to_param}, valid_session
      }.to change(Phonenumber, :count).by(-1)
    end

    it "redirects to the phonenumbers list" do
      phonenumber = Phonenumber.create! valid_attributes
      delete :destroy, {:id => phonenumber.to_param}, valid_session
      response.should redirect_to(phonenumbers_url)
    end
  end

end
